#!/usr/bin/env python3
r"""Emit LaTeX table bodies into ``paper/tables/`` from the canonical results.

Each output file is a **standalone ``tabular``** that ``paper/sections/results.tex``
can ``\input`` inside its own ``table`` float, so the caption, label, placement
and float style stay in the prose file and only the numbers are machine-written.

Usage:  ``python analysis/emit_tables.py``  ->  ``paper/tables/tab_*.tex``

Tables
------
``tab_decile.tex``        loss by income decile: £, % of income, share of the
                          total loss, households (m)
``tab_intra_decile.tex``  within-decile p10/p50/p90 loss % and the share of
                          households losing more than 5% and 10% of income
``tab_scenario.tex``      the three scenarios side by side
``tab_scorecard.tex``     the five policies on the paper's scoring metrics
``tab_region.tex``        the 12 regions: mean loss £, % of income, households
``tab_variants.tex``      the three realised-2026 specifications side by side
                          (main damped-pump, peak-fuel upper bound,
                          ONS-calibrated motor-fuel robustness), from
                          ``results/robustness/comparison.csv``

Conventions: ``booktabs`` rules only (no vertical rules), numeric columns
right-aligned (``r``), a machine-generated header comment in every file.
Requires ``\usepackage{booktabs}`` in the preamble.
"""

from __future__ import annotations

import csv
import json
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R = ROOT / "results"
OUT = ROOT / "paper" / "tables"

#: The observed shock is the paper's headline; the NIESR paths bound it.
CENTRAL_SCENARIO = "realised_2026"

#: Display order and labels for the scenario comparison table.
SCENARIO_LABELS = (
    ("niesr_baseline", "NIESR baseline"),
    ("niesr_adverse", "NIESR adverse"),
    ("realised_2026", "Realised 2026"),
)

#: Policy file stem -> short display label. Ordered as the paper argues them.
POLICY_LABELS = (
    ("social_tariff", "Social tariff"),
    ("jrf_block", "JRF block"),
    ("whd_expansion", "WHD expansion"),
    ("vat_zero", "VAT zero-rate"),
    ("ippr_rebate", "Flat rebate"),
)


def mc(*lines: str, align: str = "c") -> str:
    r"""A stacked (multi-line) column header, without needing ``makecell``.

    A nested one-column ``tabular`` bottom-aligned to the header row keeps the
    column narrow: the widest line sets the column width instead of the whole
    header running on one line. ``booktabs`` rules are unaffected.
    """
    inner = r" \\ ".join(lines)
    return r"\begin{tabular}[b]{@{}" + align + r"@{}}" + inner + r"\end{tabular}"


def small(body: list[str]) -> list[str]:
    """Group a tabular inside ``\\small`` (and slightly tighter column
    separation) so the wide numeric tables fit the text block. The caption sits
    outside the group and keeps body size.
    """
    return [r"{\small\setlength{\tabcolsep}{4.5pt}"] + body + [r"}"]


def jload(rel: str) -> dict:
    return json.loads((R / rel).read_text())


def region_label(name: str) -> str:
    """``EAST_MIDLANDS`` -> ``East Midlands``, with the usual UK exceptions."""
    words = [w.capitalize() for w in str(name).split("_")]
    fixed = {"Of": "of", "And": "and", "The": "the"}
    words = [words[0]] + [fixed.get(w, w) for w in words[1:]]
    return " ".join(words)


def decile_row(shock: dict, block: str, decile: int) -> dict:
    for row in shock[block]:
        if int(row["decile"]) == decile:
            return row
    raise KeyError(f"{block} has no decile {decile}")


def header(name: str, standalone: bool = True) -> list[str]:
    return [
        f"% {name} — machine-generated by analysis/emit_tables.py",
        f"% generated {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())} "
        f"from results/ (central scenario: {CENTRAL_SCENARIO}). DO NOT EDIT BY HAND.",
        (
            "% A standalone tabular: \\input this inside a table float that "
            "carries the caption and label. Requires \\usepackage{booktabs}."
            if standalone
            else "% A complete table float, caption and label included: the "
            "appendix inputs this directly. Requires \\usepackage{booktabs}."
        ),
    ]


def write(name: str, body: list[str], standalone: bool = True) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text("\n".join(header(name, standalone) + body) + "\n")
    print(f"wrote paper/tables/{name}")


def cost_per_pound_decile_one(policy: dict, shock: dict) -> float:
    """Total cost in £ per £1 of gain actually reaching decile one.

    The stored ``cost_per_pound_decile_one`` is £bn per £1 of *mean* decile-one
    gain; the mean is recovered from it and scaled by decile-one household
    counts to get the gain delivered to the decile as a whole.
    """
    stored = float(policy["cost_per_pound_decile_one"])
    cost_bn = float(policy["cost_bn"])
    mean_gain_d1 = cost_bn / stored
    households = float(decile_row(shock, "decile", 1)["households_m"]) * 1e6
    return cost_bn * 1e9 / (mean_gain_d1 * households)


# ---------------------------------------------------------------------------
# tables
# ---------------------------------------------------------------------------


def tab_decile(shock: dict) -> None:
    body = [
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Decile & Loss (\pounds) & Loss (\% of income) & Share of total loss (\%) "
        r"& Households (m) \\",
        r"\midrule",
    ]
    for row in shock["decile"]:
        body.append(
            f"{int(row['decile'])} & {row['mean_loss_gbp']:,.0f} & "
            f"{row['mean_loss_pct']:.2f} & {100 * row['share_of_total_loss']:.1f} & "
            f"{row['households_m']:.2f} \\\\"
        )
    body += [
        r"\midrule",
        f"All & {shock['mean_loss_gbp']:,.0f} & {shock['mean_loss_pct']:.2f} & "
        f"100.0 & {sum(r['households_m'] for r in shock['decile']):.2f} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    write("tab_decile.tex", body)


def tab_intra_decile(shock: dict) -> None:
    body = [
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        r"& \multicolumn{3}{c}{Loss (\% of income)} & "
        r"\multicolumn{2}{c}{Share of households (\%)} \\",
        r"\cmidrule(lr){2-4} \cmidrule(lr){5-6}",
        r"Decile & p10 & p50 & p90 & Losing $>$5\% & Losing $>$10\% \\",
        r"\midrule",
    ]
    for row in shock["intra_decile"]:
        body.append(
            f"{int(row['decile'])} & {row['p10_loss_pct']:.2f} & "
            f"{row['p50_loss_pct']:.2f} & {row['p90_loss_pct']:.2f} & "
            f"{100 * row['share_above_5pct']:.1f} & "
            f"{100 * row['share_above_10pct']:.1f} \\\\"
        )
    body += [r"\bottomrule", r"\end{tabular}"]
    write("tab_intra_decile.tex", body)


def tab_scenario() -> None:
    cells = []
    for key, label in SCENARIO_LABELS:
        shock = jload(f"{key}/shock.json")
        cells.append((label, shock))
    body = [
        r"\begin{tabular}{l" + "r" * len(cells) + "}",
        r"\toprule",
        " & " + " & ".join(label for label, _ in cells) + r" \\",
        r"\midrule",
    ]

    def line(name: str, fn, fmt: str = "{:.2f}") -> str:
        return name + " & " + " & ".join(fmt.format(fn(s)) for _, s in cells) + r" \\"

    body += [
        line(
            r"Aggregate additional spend (\pounds bn)",
            lambda s: s["aggregate_cost_bn"],
            "{:.1f}",
        ),
        line(r"Mean loss (\pounds)", lambda s: s["mean_loss_gbp"], "{:,.0f}"),
        line(r"Mean loss (\% of income)", lambda s: s["mean_loss_pct"]),
        r"\midrule",
        line(
            r"Decile 1 loss (\pounds)",
            lambda s: decile_row(s, "decile", 1)["mean_loss_gbp"],
            "{:,.0f}",
        ),
        line(
            r"Decile 10 loss (\pounds)",
            lambda s: decile_row(s, "decile", 10)["mean_loss_gbp"],
            "{:,.0f}",
        ),
        line(
            r"Decile 1 loss (\% of income)",
            lambda s: decile_row(s, "decile", 1)["mean_loss_pct"],
        ),
        line(
            r"Decile 10 loss (\% of income)",
            lambda s: decile_row(s, "decile", 10)["mean_loss_pct"],
        ),
        r"\midrule",
        line(
            r"Gas share of loss (\%)", lambda s: 100 * s["gas_share_of_loss"], "{:.1f}"
        ),
        line(
            r"Electricity share of loss (\%)",
            lambda s: 100 * s["electricity_share_of_loss"],
            "{:.1f}",
        ),
        line(
            r"Motor fuel share of loss (\%)",
            lambda s: 100 * s["motor_fuel_share_of_loss"],
            "{:.1f}",
        ),
        r"\bottomrule",
        r"\end{tabular}",
    ]
    write("tab_scenario.tex", body)


def tab_scorecard(shock: dict) -> None:
    body = [
        r"\begin{tabular}{lrrrrr}",
        r"\toprule",
        "Policy & "
        + mc(r"Cost", r"(\pounds bn)")
        + " & "
        + mc(r"Share to", r"deciles 1--3 (\%)")
        + " & "
        + mc(r"Cost per \pounds 1", r"to decile 1 (\pounds)")
        + " & "
        + mc(r"Losers un-", r"compensated (\%)")
        + " & "
        + mc(r"Fully com-", r"pensated (\%)")
        + r" \\",
        r"\midrule",
    ]
    for key, label in POLICY_LABELS:
        p = jload(f"{CENTRAL_SCENARIO}/{key}.json")
        body.append(
            f"{label} & {p['cost_bn']:.2f} & "
            f"{100 * p['share_to_bottom_three']:.1f} & "
            f"{cost_per_pound_decile_one(p, shock):.2f} & "
            f"{100 * p['uncompensated_share_overall']:.1f} & "
            f"{100 * p['fully_compensated_share']:.1f} \\\\"
        )
    body += [r"\bottomrule", r"\end{tabular}"]
    write("tab_scorecard.tex", small(body))


def tab_region(shock: dict) -> None:
    rows = sorted(shock["region"], key=lambda r: -r["mean_loss_pct"])
    body = [
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"Region & Mean loss (\pounds) & Mean loss (\% of income) & "
        r"Households (m) \\",
        r"\midrule",
    ]
    for row in rows:
        body.append(
            f"{region_label(row['name'])} & {row['mean_loss_gbp']:,.0f} & "
            f"{row['mean_loss_pct']:.2f} & {row['households_m']:.2f} \\\\"
        )
    body += [
        r"\midrule",
        f"United Kingdom & {shock['mean_loss_gbp']:,.0f} & "
        f"{shock['mean_loss_pct']:.2f} & "
        f"{sum(r['households_m'] for r in rows):.2f} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
    ]
    write("tab_region.tex", body)


def tab_variants() -> None:
    r"""The three realised-2026 specifications side by side.

    Read straight from ``results/robustness/comparison.csv`` (one row per
    variant) rather than re-deriving from the per-variant JSON, so the table and
    the audit trail cannot drift apart. Three numeric columns plus a label
    column fit the 6.3in text block comfortably at ``\small`` with stacked
    two-line headers.
    """
    path = R / "robustness" / "comparison.csv"
    with path.open(newline="") as fh:
        rows = {r["variant"]: r for r in csv.DictReader(fh)}
    order = (
        ("main_damped_pump", ("Main", "specification")),
        ("upper_bound_peak_fuel", ("Peak-fuel", "upper bound")),
        ("robustness_ons_fuel", ("ONS-calibrated", "motor fuel")),
    )
    cols = [rows[key] for key, _ in order if key in rows]
    if not cols:
        raise KeyError(f"{path} has none of the expected variants")

    def line(name: str, fn, fmt: str = "{:.2f}") -> str:
        return name + " & " + " & ".join(fmt.format(fn(r)) for r in cols) + r" \\"

    def num(column: str):
        return lambda r: float(r[column])

    def pct(column: str):
        return lambda r: 100 * float(r[column])

    body = [
        r"\begin{tabular}{l" + "r" * len(cols) + "}",
        r"\toprule",
        " & " + " & ".join(mc(*head) for _, head in order[: len(cols)]) + r" \\",
        r"\midrule",
        line(
            r"Aggregate additional spend (\pounds bn)",
            num("aggregate_cost_bn"),
            "{:.2f}",
        ),
        line(r"Mean loss (\pounds)", num("mean_loss_gbp"), "{:,.0f}"),
        line(r"Mean loss (\% of income)", num("mean_loss_pct")),
        r"\midrule",
        line(r"Decile 1 loss (\pounds)", num("decile1_loss_gbp"), "{:,.0f}"),
        line(r"Decile 1 loss (\% of income)", num("decile1_loss_pct")),
        line(r"Decile 10 loss (\pounds)", num("decile10_loss_gbp"), "{:,.0f}"),
        line(r"Decile 10 loss (\% of income)", num("decile10_loss_pct")),
        line(r"Decile 1/10 ratio (\% of income)", num("d1_d10_ratio_pct")),
        r"\midrule",
        line(r"Gas share of loss (\%)", pct("gas_share_of_loss"), "{:.1f}"),
        line(
            r"Electricity share of loss (\%)",
            pct("electricity_share_of_loss"),
            "{:.1f}",
        ),
        line(
            r"Motor fuel share of loss (\%)", pct("motor_fuel_share_of_loss"), "{:.1f}"
        ),
        r"\bottomrule",
        r"\end{tabular}",
    ]
    write("tab_variants.tex", small(body))


# ---------------------------------------------------------------------------
# appendix sweep tables (results/sensitivity/*.csv)
# ---------------------------------------------------------------------------

SENS = R / "sensitivity"


def sload(name: str) -> list[dict]:
    with (SENS / name).open(newline="") as fh:
        return list(csv.DictReader(fh))


def float_wrap(body: list[str], caption: str, label: str) -> list[str]:
    """Wrap a tabular in its own float.

    The appendix inputs these three files directly rather than inside a
    ``table`` environment of its own, so the caption and label live here.
    """
    return (
        [
            r"\begin{table}[htbp]",
            r"\centering",
            f"\\caption{{{caption}}}",
            f"\\label{{{label}}}",
        ]
        + body
        + [r"\end{table}"]
    )


#: Display names for the named elasticity specifications, in sweep order.
ELASTICITY_LABELS = {
    "labandeira_short_run": "Labandeira et al., short run",
    "labandeira_long_run": "Labandeira et al., long run",
    "priesmann_short_run": "Priesmann \\& Praktiknjo, short run",
    "priesmann_long_run": "Priesmann \\& Praktiknjo, long run",
    "prior_repo_replication": "Prior-repo replication",
}


def minus(text: str) -> str:
    """ASCII hyphen -> LaTeX math minus, for numeric cells only."""
    return text.replace("-", "$-$")


def elasticity_label(row: dict) -> str:
    spec = row["spec"]
    if spec in ELASTICITY_LABELS:
        return ELASTICITY_LABELS[spec]
    eps = float(row["epsilon_mean"])
    if eps == 0:
        return r"Flat $\varepsilon = 0$ (main spec.)"
    # already inside math mode, so the ASCII hyphen renders as a minus
    return f"Flat $\\varepsilon = {eps:.1f}$"


def tab_elasticity() -> None:
    rows = sload("elasticity.csv")
    body = [
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        "Specification & "
        + mc(r"Mean", r"$\varepsilon$")
        + " & "
        + mc(r"Mean loss", r"(\pounds)")
        + " & "
        + mc(r"Loss", r"(\% inc.)")
        + " & "
        + mc(r"Aggregate", r"(\pounds bn)")
        + " & "
        + mc(r"Decile 1", r"(\%)")
        + " & "
        + mc(r"Decile 10", r"(\%)")
        + r" \\",
        r"\midrule",
    ]
    for row in rows:
        cells = [
            minus(f"{float(row['epsilon_mean']):.2f}"),
            f"{float(row['mean_loss_gbp']):,.0f}",
            f"{float(row['mean_loss_pct']):.2f}",
            f"{float(row['aggregate_loss_bn']):.2f}",
            f"{float(row['decile1_loss_pct']):.2f}",
            f"{float(row['decile10_loss_pct']):.2f}",
        ]
        body.append(elasticity_label(row) + " & " + " & ".join(cells) + r" \\")
    body += [r"\bottomrule", r"\end{tabular}"]
    write(
        "tab_elasticity.tex",
        float_wrap(
            small(body),
            "Demand-response sweep, realised 2026 scenario. The main "
            "specification is zero elasticity, an explicit upper bound on the "
            "welfare loss; every other row is a robustness check, not an "
            "alternative headline. The level of the loss moves by a factor of "
            "five across the grid; the qualitative decile ordering does not move "
            "at all.",
            "tab:elasticity",
        ),
        standalone=False,
    )


def tab_caplag() -> None:
    rows = sload("cap_lag.csv")
    body = [
        r"\begin{tabular}{llrrrrr}",
        r"\toprule",
        r"& & \multicolumn{2}{c}{Annualised 2026} & "
        r"\multicolumn{2}{c}{Cumulative} & \\",
        r"\cmidrule(lr){3-4} \cmidrule(lr){5-6}",
        mc(r"Lag", r"(quarters)", align="l")
        + " & "
        + mc(r"First cap", r"quarter", align="l")
        + " & "
        + mc(r"Mean", r"(\pounds)")
        + " & "
        + mc(r"Total", r"(\pounds bn)")
        + " & "
        + mc(r"Mean", r"(\pounds)")
        + " & "
        + mc(r"Total", r"(\pounds bn)")
        + " & "
        + mc(r"Motor fuel", r"(\pounds bn)")
        + r" \\",
        r"\midrule",
    ]
    for row in rows:
        lag = int(row["lag_quarters"])
        tag = f"{lag} (paper)" if lag == 3 else str(lag)
        body.append(
            f"{tag} & {row['first_cap_quarter']} & "
            f"{float(row['annualised_mean_loss_gbp']):,.0f} & "
            f"{float(row['annualised_loss_bn']):.2f} & "
            f"{float(row['cumulative_mean_loss_gbp']):,.0f} & "
            f"{float(row['cumulative_loss_bn']):.2f} & "
            f"{float(row['motor_fuel_bn']):.2f} \\\\"
        )
    body += [r"\bottomrule", r"\end{tabular}"]
    write(
        "tab_caplag.tex",
        float_wrap(
            small(body),
            "Wholesale-to-retail lag sweep, realised 2026 scenario. The "
            "cumulative loss is exactly invariant to the lag; only the "
            "calendar-year attribution moves. The annualised column is therefore "
            "an accounting statement about which year the bill lands in, not a "
            "statement about the size of the shock.",
            "tab:caplag",
        ),
        standalone=False,
    )


def tab_asymmetry() -> None:
    rows = sload("asymmetry.csv")
    body = [
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        mc(r"Marginal-", r"pricing share", align="l")
        + " & "
        + mc(r"Electricity", r"factor")
        + " & "
        + mc(r"Mean loss", r"(\pounds)")
        + " & "
        + mc(r"Loss", r"(\% inc.)")
        + " & "
        + mc(r"Decile", r"1/10 ratio")
        + " & "
        + mc(r"Gas share of", r"domestic loss (\%)")
        + " & "
        + mc(r"Aggregate", r"(\pounds bn)")
        + r" \\",
        r"\midrule",
    ]
    for row in rows:
        share = float(row["marginal_pricing_share"])
        tag = (
            f"{share:.2f} (paper)"
            if row["is_paper_central"] == "True"
            else f"{share:.2f}"
        )
        body.append(
            f"{tag} & {float(row['electricity_price_factor']):.4f} & "
            f"{float(row['mean_loss_gbp']):,.0f} & "
            f"{float(row['mean_loss_pct']):.2f} & "
            f"{float(row['decile_ratio_pct']):.2f} & "
            f"{100 * float(row['gas_share_of_domestic_loss']):.1f} & "
            f"{float(row['aggregate_loss_bn']):.2f} \\\\"
        )
    body += [r"\bottomrule", r"\end{tabular}"]
    write(
        "tab_asymmetry.tex",
        float_wrap(
            small(body),
            "Marginal-pricing-share sweep, realised 2026 scenario. The gas "
            "price factor is held at 1.1404 throughout; only the electricity "
            "pass-through varies. The headline incidence barely moves, while the "
            "composition of the domestic loss moves materially.",
            "tab:asymmetry",
        ),
        standalone=False,
    )


def main() -> None:
    shock = jload(f"{CENTRAL_SCENARIO}/shock.json")
    tab_decile(shock)
    tab_intra_decile(shock)
    tab_scenario()
    tab_scorecard(shock)
    tab_region(shock)
    tab_variants()
    tab_elasticity()
    tab_caplag()
    tab_asymmetry()


if __name__ == "__main__":
    main()
